# Generated by Django 4.1.3 on 2023-02-08 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("effectiveness", "0002_alter_effectiveness_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="effectivenesssemester",
            name="evaluator",
        ),
    ]
