# Generated by Django 4.1.3 on 2023-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='notificado*'),
        ),
    ]
