# Generated by Django 4.1.3 on 2023-11-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0002_userapp_notificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='notificado',
        ),
    ]
