# Generated by Django 2.2.7 on 2020-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0004_auto_20201124_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='image',
            field=models.ImageField(default='static/users/userDefault1.png', null=True, upload_to='static/users', verbose_name='Avatar'),
        ),
    ]
