# Generated by Django 4.1.3 on 2023-12-07 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0004_userapp_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='fecha_frase',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 7, 20, 16, 46, 916353), verbose_name="Fecha de última frase'"),
        ),
    ]
