# Generated by Django 4.1.3 on 2023-12-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0005_userapp_fecha_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='fecha_frase',
            field=models.DateTimeField(verbose_name="Fecha de última frase'"),
        ),
    ]
