# Generated by Django 2.2.7 on 2020-11-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0006_auto_20201124_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='image',
            field=models.ImageField(default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Avatar'),
        ),
    ]
