# Generated by Django 4.1.3 on 2023-12-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoBaseApp', '0007_alter_userapp_fecha_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='frase',
            field=models.CharField(max_length=255, null=True, verbose_name='frase'),
        ),
    ]
