# Generated by Django 4.1.3 on 2023-02-07 16:53

import apps.licenses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="license",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.licenses.models.model_upload_image,
                verbose_name="Subir Documento",
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z áÁéÉíÍóÓúÚñÑ.]*[a-zA-Z áÁéÉíÍóÓúÚñÑ.]$",
                        message="Solo puede ingresar letras",
                    )
                ],
                verbose_name="Nombre Documento",
            ),
        ),
    ]
