# Generated by Django 4.1.3 on 2023-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wayofreception",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
    ]
