# Generated by Django 4.1.3 on 2023-02-07 16:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="client",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z áÁéÉíÍóÓúÚñÑ.]*[a-zA-Z áÁéÉíÍóÓúÚñÑ.]$",
                        message="Solo puede ingresar letras",
                    )
                ],
                verbose_name="Cliente",
            ),
        ),
    ]
