# Generated by Django 4.1.3 on 2023-04-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0002_alter_complaint_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "PENDIENTE"),
                    (2, "EN PROCESO"),
                    (3, "CERRADA"),
                    (4, "NO PROCEDE"),
                ],
                default=1,
                verbose_name="Estado",
            ),
        ),
    ]
