# Generated by Django 4.1.3 on 2023-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0003_alter_complaint_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(1, "EN PROCESO"), (2, "CERRADA"), (3, "NO PROCEDE")],
                default=1,
                verbose_name="Estado",
            ),
        ),
    ]
