# Generated by Django 4.1.3 on 2024-05-07 14:22

import SISGDDO.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logoentity',
            name='logo1',
            field=models.ImageField(storage=SISGDDO.storage.OverwriteStorage(), upload_to='media/logo/', verbose_name='Logo principal'),
        ),
        migrations.AlterField(
            model_name='logoentity',
            name='logo2',
            field=models.ImageField(storage=SISGDDO.storage.OverwriteStorage(), upload_to='media/logo/', verbose_name='Logo secundario'),
        ),
    ]
