# Generated by Django 4.1.3 on 2023-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_delete_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="acronym",
            field=models.CharField(max_length=3, verbose_name="Siglas"),
        ),
        migrations.AlterField(
            model_name="country",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="position",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
    ]
