# Generated by Django 4.1.3 on 2023-01-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_procedure_responsible_process_responsible_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="prefix",
            field=models.CharField(
                blank=True,
                default="",
                max_length=15,
                null=True,
                verbose_name="Categoría Científica",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="identification",
            field=models.CharField(
                blank=True,
                max_length=11,
                null=True,
                verbose_name="Carnet de indentidad",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Apellidos"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="base.position",
                verbose_name="Cargo",
            ),
        ),
    ]
