# Generated by Django 4.1.3 on 2023-02-07 16:53

import apps.base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_employee_prefix_alter_employee_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procedure",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.base.models.model_upload_image,
                verbose_name="Subir Archivo",
            ),
        ),
    ]
