# Generated by Django 4.1.3 on 2023-02-08 09:48

import SISGDDO.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_process_responsible"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "logo1",
                    models.ImageField(
                        storage=SISGDDO.storage.OverwriteStorage(),
                        upload_to="logo/",
                        verbose_name="Logo principal",
                    ),
                ),
                (
                    "logo2",
                    models.ImageField(
                        storage=SISGDDO.storage.OverwriteStorage(),
                        upload_to="logo/",
                        verbose_name="Logo secundario",
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
