# Generated by Django 4.1.3 on 2023-04-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_process_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="procedure",
            options={"ordering": ("process__order", "abbreviation", "name")},
        ),
        migrations.AlterModelOptions(
            name="process",
            options={"ordering": ("order",)},
        ),
    ]
