# Generated by Django 4.1.3 on 2023-06-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("iproperty", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeLegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nombre")),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name="industrialproperty",
            name="type_legal_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="iproperty.typelegaldocument",
                verbose_name="Tipo de documento legal",
            ),
        ),
    ]
