# Generated by Django 4.1.3 on 2023-02-07 16:53

import apps.iproperty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iproperty", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industrialproperty",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.iproperty.models.model_upload_image,
                verbose_name="Subir Archivo",
            ),
        ),
    ]
