# Generated by Django 4.1.3 on 2023-06-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iproperty", "0002_typelegaldocument_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drawingclassification",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="figurativeelementclassification",
            name="number",
            field=models.CharField(
                default="0.0.0", max_length=10, unique=True, verbose_name="Código"
            ),
        ),
        migrations.AlterField(
            model_name="patentclassification",
            name="name",
            field=models.CharField(max_length=150, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="productclassification",
            name="number",
            field=models.PositiveIntegerField(
                default=0, unique=True, verbose_name="Código"
            ),
        ),
    ]
