# Generated by Django 4.1.3 on 2023-06-08 23:26

import SISGDDO.models
import SISGDDO.storage
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accion_realizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha acción realizada*')),
                ('nombre_accion', models.CharField(max_length=150, verbose_name='Nombre acción*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, null=True, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='auditoria_interna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de auditoría*')),
                ('titulo', models.CharField(max_length=150, null=True, verbose_name='Título del informe*')),
                ('objetivos', models.CharField(blank=True, max_length=250, null=True, verbose_name='Objetivos de la auditoría')),
                ('alcance', models.CharField(blank=True, max_length=250, null=True, verbose_name='Alcance de la auditoría')),
                ('criterios', models.CharField(blank=True, max_length=250, null=True, verbose_name='Criterios de la auditoría')),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones de la auditoría')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='CambiarLogotipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(default='2023-06-08', verbose_name='Fecha de Cambio del Logotipo')),
                ('logo', models.ImageField(storage=SISGDDO.storage.OverwriteStorage(), upload_to='logo/', verbose_name='Logo*')),
            ],
        ),
        migrations.CreateModel(
            name='consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10, null=True, unique=True, verbose_name='número*')),
                ('codigo', models.CharField(max_length=10, null=True, unique=True, verbose_name='código*')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='fecha de entrada*')),
                ('nombre_proyecto', models.CharField(max_length=250, null=True, unique=True, verbose_name='nombre*')),
                ('aprobacion_consejo', models.CharField(blank=True, max_length=25, null=True, verbose_name='aprobación Consejo Editorial')),
                ('fecha_aprobacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de aprobación Consejo Editorial')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*')),
                ('fecha_interrupcion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de interrupción')),
                ('causa_interrupcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='causa de la interrupción')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('fecha_extension', models.DateField(blank=True, null=True, verbose_name='fecha de extensión')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('costo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999999)], verbose_name='costo*')),
                ('observacion', models.CharField(blank=True, max_length=250, null=True, verbose_name='observacion')),
                ('informe_apertura', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.consecutivo.ruta, verbose_name='informe apertura')),
                ('informe_cierre', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.consecutivo.ruta, verbose_name='informe cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('area', models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='área*')),
            ],
        ),
        migrations.CreateModel(
            name='entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_acuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_cenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='estado_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_curso', models.CharField(max_length=25, verbose_name='Estado del curso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='estado_entradas_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_indicador_objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='fuente_financiamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='linea_tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='nombre')),
                ('anno', models.CharField(blank=True, max_length=4, null=True, verbose_name='año')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='modo_formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacion', models.CharField(max_length=25, verbose_name='Modo de formación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='nombre*')),
                ('fecha_definicion', models.DateField(verbose_name='fecha de definición*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='permisos_personalizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('grafico_RH', 'Ver grafico de RRHH'), ('grafico_Cap', 'Ver grafico de CAP'), ('grafico_CA', 'Ver grafico de C y A'), ('grafico_D', 'Ver grafico de Direccion'), ('grafico_I', 'Ver grafico de Inform'), ('grafico_Admin', 'Ver grafico de Admin')],
            },
        ),
        migrations.CreateModel(
            name='PlanesdeTrabajo',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='No.*')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripcion*')),
                ('fecha', models.DateTimeField(blank=True, verbose_name='Fecha de Reunion*')),
                ('hora', models.TimeField(blank=True, verbose_name='Hora Programada*')),
                ('lugar', models.CharField(max_length=80, verbose_name='Lugar Previsto*')),
            ],
        ),
        migrations.CreateModel(
            name='proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10, null=True, unique=True, verbose_name='número*')),
                ('codigo', models.CharField(max_length=10, null=True, unique=True, verbose_name='código*')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='fecha de entrada*')),
                ('nombre_proyecto', models.CharField(max_length=250, null=True, unique=True, verbose_name='nombre*')),
                ('aprobacion_consejo', models.CharField(blank=True, max_length=25, null=True, verbose_name='aprobación Consejo Editorial')),
                ('fecha_aprobacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de aprobación Consejo Editorial')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*')),
                ('fecha_interrupcion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='fecha de interrupción')),
                ('causa_interrupcion', models.CharField(blank=True, max_length=250, null=True, verbose_name='causa de la interrupción')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('fecha_extension', models.DateField(blank=True, null=True, verbose_name='fecha de extensión')),
                ('fecha_cierre', models.DateField(null=True, verbose_name='fecha de cierre*')),
                ('costo', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999999)], verbose_name='costo*')),
                ('observacion', models.CharField(blank=True, max_length=250, null=True, verbose_name='observacion')),
                ('informe_apertura', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.proyecto.ruta, verbose_name='informe apertura')),
                ('informe_cierre', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.proyecto.ruta, verbose_name='informe cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('area', models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='área*')),
                ('consecutivo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto', to='SISGDDO.consecutivo', verbose_name='consecutivo*')),
                ('estado', models.ForeignKey(on_delete=models.SET('Estado eliminado de la BD'), to='SISGDDO.estado_proyecto', verbose_name='estado*')),
                ('formato', models.ManyToManyField(related_name='formatos_proyecto', to='SISGDDO.formato', verbose_name='formato')),
                ('fuente_financiamiento', models.ForeignKey(null=True, on_delete=models.SET('Fuente de financiamiento eliminada de la BD'), to='SISGDDO.fuente_financiamiento', verbose_name='fuente de financiamiento*')),
                ('linea_tematica', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Línea temática eliminada de la BD'), to='SISGDDO.linea_tematica', verbose_name='línea temática')),
            ],
        ),
        migrations.CreateModel(
            name='rol_trabajador_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_codigo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_de_obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.CreateModel(
            name='via_recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Nombre vía de recepción*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
            ],
        ),
        migrations.CreateModel(
            name='conclusion_adicional',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.proyecto')),
                ('fecha', models.DateField(verbose_name='Fecha de la conclusión adicional*')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion de la conclusión adicional')),
            ],
            bases=('SISGDDO.proyecto',),
        ),
        migrations.CreateModel(
            name='dato_adicional',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.proyecto')),
                ('fecha', models.DateField(verbose_name='Fecha del dato adicional*')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion del dato adicional')),
            ],
            bases=('SISGDDO.proyecto',),
        ),
        migrations.CreateModel(
            name='trabajador_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proyecto', verbose_name='proyecto*')),
                ('rol', models.ForeignKey(on_delete=models.SET('Rol eliminado de la BD'), to='SISGDDO.rol_trabajador_proyecto', verbose_name='rol*')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='trabajador*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.consecutivo', verbose_name='consecutivo*')),
                ('rol', models.ForeignKey(on_delete=models.SET('Rol eliminado de la BD'), to='SISGDDO.rol_trabajador_proyecto', verbose_name='rol*')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='trabajador*')),
            ],
        ),
        migrations.CreateModel(
            name='sosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_salva', models.CharField(max_length=10, verbose_name='número*')),
                ('fecha', models.DateField(default='2023-06-08', verbose_name='fecha de entrega*')),
                ('anno', models.CharField(blank=True, max_length=4, null=True, verbose_name='año')),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='autor')),
                ('ubicacion_salva', models.CharField(blank=True, max_length=3, null=True, verbose_name='ubicación')),
                ('observaciones', models.CharField(blank=True, max_length=150, null=True, verbose_name='observaciones')),
                ('archivo', models.FileField(null=True, upload_to='sosi/', verbose_name='archivo')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('consecutivo', models.OneToOneField(null=True, on_delete=models.SET('Consecutivo eliminado de la BD'), related_name='sosi', to='SISGDDO.consecutivo', verbose_name='consecutivo*')),
                ('especialista', models.ForeignKey(on_delete=models.SET('Trabajador eliminado'), to='base.employee', verbose_name='trabajador que entrega*')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de proyecto eliminado de la Base de datos'), to='SISGDDO.tipo_proyecto', verbose_name='tipo de proyecto*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo_codigo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de código eliminado de la Base de datos'), to='SISGDDO.tipo_codigo', verbose_name='tipo de código*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='trabajador',
            field=models.ManyToManyField(through='SISGDDO.trabajador_proyecto', to='base.employee', verbose_name='rol en el proyecto*'),
        ),
        migrations.CreateModel(
            name='proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, null=True, unique=True, verbose_name='Nombre del proceso*')),
                ('abreviatura', models.CharField(max_length=3, verbose_name='Abreviatura*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('responsable', models.ManyToManyField(to='base.employee', verbose_name='Responsable*')),
            ],
        ),
        migrations.CreateModel(
            name='premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='nombre*')),
                ('fecha', models.DateTimeField(default=datetime.datetime.now, verbose_name='fecha*')),
                ('archivo', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.premio.ruta, verbose_name='planilla de la Reserva')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('entidad', models.ForeignKey(on_delete=models.SET('CITMATEL'), to='SISGDDO.entidad', verbose_name='entidad*')),
            ],
        ),
        migrations.CreateModel(
            name='indicador_objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, null=True, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('estado', models.ForeignKey(null=True, on_delete=models.SET('Estado eliminado'), to='SISGDDO.estado_indicador_objetivos', verbose_name='estado*')),
                ('objetivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='SISGDDO.objetivo', verbose_name='objetivo*')),
            ],
        ),
        migrations.CreateModel(
            name='incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de recepcion de la incidencia*')),
                ('fecha_cierre', models.DateField(blank=True, null=True, verbose_name='Fecha de cierre de la incidencia')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción de la incidencia*')),
                ('respuesta', models.TextField(blank=True, max_length=250, null=True, verbose_name='Respuesta dada a la incidencia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('trabajador', models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado'), to='base.employee', verbose_name='Trabajador que reporta la incidencia*')),
            ],
        ),
        migrations.CreateModel(
            name='entrada_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='fecha*')),
                ('fecha_salida', models.DateField(null=True, verbose_name='Fecha de salida')),
                ('dictamen', models.FileField(blank=True, null=True, upload_to='entradas_proyectos/', verbose_name='informe apertura')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('entregado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Trabajador que entrega')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SISGDDO.estado_entradas_proyecto', verbose_name='Estado entrada proyecto')),
                ('formato', models.ManyToManyField(to='SISGDDO.formato', verbose_name='Formato*')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proyecto', verbose_name='Proyecto*')),
            ],
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre del curso*')),
                ('fecha_inicio', models.DateField(null=True, verbose_name='Fecha de inicio*')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('duracion_diaria', models.IntegerField(blank=True, null=True, verbose_name='Duración del curso en horas')),
                ('precio', models.FloatField(blank=True, null=True, verbose_name='Precio del curso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('entidad', models.ForeignKey(null=True, on_delete=models.SET('Entidad eliminada'), to='SISGDDO.entidad', verbose_name='Entidad*')),
                ('estado_curso', models.ForeignKey(null=True, on_delete=models.SET('Estado del curso eliminado'), to='SISGDDO.estado_curso', verbose_name='Estado del curso')),
                ('modo_formacion', models.ForeignKey(null=True, on_delete=models.SET('Modo de formación eliminado de la BD'), to='SISGDDO.modo_formacion', verbose_name='Modo de formación*')),
            ],
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='estado',
            field=models.ForeignKey(on_delete=models.SET('Estado eliminado de la BD'), to='SISGDDO.estado_proyecto', verbose_name='estado*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='formato',
            field=models.ManyToManyField(related_name='formatos_consecutivo', to='SISGDDO.formato', verbose_name='formato'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='fuente_financiamiento',
            field=models.ForeignKey(null=True, on_delete=models.SET('Fuente de financiamiento eliminada de la BD'), to='SISGDDO.fuente_financiamiento', verbose_name='fuente de financiamiento*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='linea_tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Línea temática eliminada de la BD'), to='SISGDDO.linea_tematica', verbose_name='línea temática'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de proyecto eliminado de la Base de datos'), to='SISGDDO.tipo_proyecto', verbose_name='tipo de proyecto*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='tipo_codigo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de código eliminado de la Base de datos'), to='SISGDDO.tipo_codigo', verbose_name='tipo de código*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='trabajador',
            field=models.ManyToManyField(through='SISGDDO.trabajador_consecutivo', to='base.employee', verbose_name='rol en el proyecto*'),
        ),
        migrations.CreateModel(
            name='auditoria_externa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True, verbose_name='Fecha de emisión*')),
                ('registro', models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de registro*')),
                ('titulo', models.CharField(max_length=150, null=True, verbose_name='Título del informe*')),
                ('resultados', models.BooleanField(default=True, verbose_name='Resultado')),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('informe', models.FileField(blank=True, null=True, upload_to='dictamenes/', verbose_name='Informe de la auditoria*')),
                ('plan_medidas', models.FileField(blank=True, null=True, upload_to='dictamenes/', verbose_name='Plan de medidas*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('entidad', models.ForeignKey(on_delete=models.SET('Entidad eliminada'), to='SISGDDO.entidad', verbose_name='Entidad*')),
            ],
        ),
        migrations.CreateModel(
            name='Afectaciones',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='No.*')),
                ('fecha_recepcion', models.DateTimeField(blank=True, verbose_name='Fecha de Entrada*')),
                ('afectacion', models.CharField(max_length=80, verbose_name='Afectacion reportada*')),
                ('mesplaneado', models.DateField(blank=True, verbose_name='Mes Planeado Resolverse*')),
                ('fechacierre', models.DateTimeField(blank=True, verbose_name='Fecha de cierre*')),
                ('observacionesactual', models.CharField(max_length=250, verbose_name='Observaciones*')),
                ('observacionesfutura', models.CharField(max_length=250, verbose_name='Observaciones*')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado*')),
                ('propuesto', models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), related_name='propuesto', to='base.employee', verbose_name='Promotor de Afeccion*')),
                ('responsable', models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), related_name='responsable', to='base.employee', verbose_name='Responsable de Afeccion*')),
            ],
        ),
        migrations.CreateModel(
            name='acuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, null=True, unique=True, verbose_name='Número de acuerdo*')),
                ('nombre', models.CharField(max_length=25, null=True, verbose_name='Nombre del acuerdo*')),
                ('fecha', models.DateField(verbose_name='fecha*')),
                ('fecha_limite', models.DateField(null=True, verbose_name='fecha límite para cumplir')),
                ('fecha_cumplimiento', models.DateField(null=True, verbose_name='fecha de cumplimiento')),
                ('observaciones', models.TextField(null=True, verbose_name='observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('estado', models.ForeignKey(null=True, on_delete=models.SET('Estado eliminado'), to='SISGDDO.estado_acuerdo', verbose_name='estado de acuerdo*')),
                ('trabajador', models.ManyToManyField(to='base.employee', verbose_name='responsable*')),
            ],
        ),
        migrations.CreateModel(
            name='accion_indicador_objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo*')),
                ('area', models.ForeignKey(null=True, on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='área*')),
                ('indicador', models.ForeignKey(null=True, on_delete=models.SET('Indicador eliminado de la BD'), related_name='accion', to='SISGDDO.indicador_objetivos', verbose_name='indicador*')),
            ],
        ),
    ]
