# Generated by Django 4.1.3 on 2024-02-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('SISGDDO', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividadplan',
            name='preside',
        ),
        migrations.AlterField(
            model_name='afectaciones',
            name='observacionesactual',
            field=models.CharField(max_length=250, verbose_name='Seguimiento'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2024-02-07', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='hora',
            field=models.TimeField(default='00:00', verbose_name='Hora de recepción'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='respuesta',
            field=models.TextField(max_length=250, null=True, verbose_name='Seguimiento'),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('activo', models.BooleanField(auto_created=True, default=True, verbose_name='Activo')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre de Contacto')),
                ('relacionados', models.ManyToManyField(blank=True, to='base.employee', verbose_name='Trabajadores de contacto')),
            ],
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='preside',
            field=models.ManyToManyField(blank=True, related_name='presiden', to='base.employee', verbose_name='Trabajadores que presiden'),
        ),
    ]
