# Generated by Django 4.1.3 on 2022-12-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sosi',
            old_name='eliminado',
            new_name='activo',
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-12-11', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-12-11', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(default='2022-12-11', verbose_name='fecha de entrega*'),
        ),
    ]
