# Generated by Django 2.2.7 on 2020-11-26 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0002_atencion_cliente_externo_incidencias_reserva_cuadro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='documento',
            field=models.FileField(upload_to='dictamenes', verbose_name='Documento*'),
        ),
        migrations.AlterField(
            model_name='reserva_cuadro',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto/', verbose_name='Imagen*'),
        ),
        migrations.AlterField(
            model_name='reserva_cuadro',
            name='planilla',
            field=models.FileField(null=True, upload_to='planillas/', verbose_name='Planilla*'),
        ),
        migrations.AlterField(
            model_name='tipo_de_licencias',
            name='observacion',
            field=models.TextField(max_length=55, null=True, verbose_name='Observación*'),
        ),
        migrations.AlterField(
            model_name='valoracion_encuesta',
            name='documento',
            field=models.FileField(upload_to='valoracion_encuesta/', verbose_name='Valoración de Encuesta*'),
        ),
    ]
