# Generated by Django 4.1.3 on 2023-06-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SISGDDO", "0002_alter_cambiarlogotipo_fecha_cambio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cambiarlogotipo",
            name="fecha_cambio",
            field=models.DateField(
                default="2023-06-11", verbose_name="Fecha de Cambio del Logotipo"
            ),
        ),
        migrations.AlterField(
            model_name="eficacia",
            name="anno",
            field=models.DateField(
                default="2023-06-11", verbose_name="Año análisis de eficacia*"
            ),
        ),
        migrations.AlterField(
            model_name="sosi",
            name="fecha",
            field=models.DateField(
                default="2023-06-11", verbose_name="fecha de entrega*"
            ),
        ),
    ]
