# Generated by Django 4.1.3 on 2024-02-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0002_remove_actividadplan_preside_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadplan',
            name='contacto',
            field=models.ManyToManyField(blank=True, related_name='contactos', to='SISGDDO.contacto', verbose_name='Grupo de Contacto'),
        ),
        migrations.AddField(
            model_name='actividadplan',
            name='contcheck',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Usar contactos'),
        ),
        migrations.AddField(
            model_name='afectaciones',
            name='observacion',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Seguimiento agregado'),
        ),
        migrations.AlterField(
            model_name='actividadplan',
            name='otro',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Otro Lugar'),
        ),
        migrations.AlterField(
            model_name='afectaciones',
            name='observacionesactual',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Seguimiento'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2024-02-23', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
