# Generated by Django 2.2.7 on 2023-02-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0002_rename_eliminado_sosi_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2023-02-16', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2023-02-16', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(default='2023-02-16', verbose_name='fecha de entrega*'),
        ),
    ]
