# Generated by Django 4.1.3 on 2024-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0003_actividadplan_contacto_actividadplan_contcheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2024-04-02', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
