# Generated by Django 2.2.7 on 2020-11-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0003_auto_20201126_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='no_conformidad',
            name='nombre_conformifdad',
            field=models.CharField(max_length=55, verbose_name='Nombre_conformidad'),
        ),
    ]
