# Generated by Django 2.2.7 on 2020-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0004_auto_20201127_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva_cuadro',
            name='foto',
            field=models.ImageField(default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Imagen*'),
        ),
        migrations.AlterField(
            model_name='reserva_cuadro',
            name='planilla',
            field=models.FileField(default='foto/userDefault1.png', null=True, upload_to='planillas/', verbose_name='Planilla*'),
        ),
    ]
