# Generated by Django 2.2.7 on 2020-11-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0005_auto_20201127_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(max_length=11, verbose_name='Carnet de Identidad*'),
        ),
    ]
