# Generated by Django 2.2.7 on 2020-12-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0006_auto_20201127_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reserva_cuadro',
        ),
    ]
