# Generated by Django 2.2.7 on 2020-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0007_delete_reserva_cuadro'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='es_cuadro',
            field=models.BooleanField(default=True, null=True, verbose_name='Es Cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='es_reserva',
            field=models.BooleanField(default=True, null=True, verbose_name='Es Reserva'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fotocuadro',
            field=models.ImageField(default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Imagen del Cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fotoreserva',
            field=models.ImageField(default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Imagen de la Reserva'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='planillacuadro',
            field=models.FileField(default='foto/userDefault1.png', null=True, upload_to='planillas/', verbose_name='Planilla del Cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='planillareserva',
            field=models.FileField(default='foto/userDefault1.png', null=True, upload_to='planillas/', verbose_name='Planilla de la Reserva'),
        ),
    ]
