# Generated by Django 2.2.7 on 2020-12-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0008_auto_20201202_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='es_cuadro',
            field=models.BooleanField(default=False, null=True, verbose_name='Es Cuadro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='es_reserva',
            field=models.BooleanField(default=False, null=True, verbose_name='Es Reserva'),
        ),
    ]
