# Generated by Django 4.1.4 on 2023-05-14 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0003_auto_20230216_0301'),
        ('SISGDDO', '0009_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
    ]
