# Generated by Django 2.2.7 on 2020-12-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0012_auto_20201202_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='nombre_Proceso',
            field=models.CharField(max_length=55, unique=True, verbose_name='Nombre del Proceso*'),
        ),
    ]
