# Generated by Django 2.2.7 on 2020-12-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0013_auto_20201204_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre_Area',
            field=models.CharField(max_length=55, unique=True, verbose_name='Nombre del Área'),
        ),
    ]
