# Generated by Django 4.1.4 on 2023-05-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0014_remove_incidencia_estado_remove_incidencia_proceso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2023-05-16', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2023-05-16', verbose_name='Año análisis de eficacia*'),
        ),
    ]
