# Generated by Django 2.2.7 on 2020-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0015_auto_20201210_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_dictamen',
            name='nombre_Estado',
            field=models.CharField(max_length=25, verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='estado_entradas_proyecto',
            name='nombre_Estado',
            field=models.CharField(max_length=25, verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='estado_no_conformidad',
            name='nombre_Estado',
            field=models.CharField(max_length=25, verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='estado_proyecto',
            name='nombre_Estado',
            field=models.CharField(max_length=25, verbose_name='Estado*'),
        ),
    ]
