<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-06-05 12:50
=======
# Generated by Django 4.1.3 on 2023-05-24 05:15
>>>>>>> 8d3893d750f2dd0ff63cb37051a2d170c247ca6d

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0017_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
<<<<<<< HEAD
            field=models.DateField(default='2023-06-05', verbose_name='Fecha de Cambio del Logotipo'),
=======
            field=models.DateField(default='2023-05-24', verbose_name='Fecha de Cambio del Logotipo'),
>>>>>>> 8d3893d750f2dd0ff63cb37051a2d170c247ca6d
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
<<<<<<< HEAD
            field=models.DateField(default='2023-06-05', verbose_name='Año análisis de eficacia*'),
=======
            field=models.DateField(default='2023-05-24', verbose_name='Año análisis de eficacia*'),
>>>>>>> 8d3893d750f2dd0ff63cb37051a2d170c247ca6d
        ),
    ]
