# Generated by Django 4.1.3 on 2023-06-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('SISGDDO', '0018_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='planesdetrabajo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='planesdetrabajo',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='planesdetrabajo',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='planesdetrabajo',
            name='lugar',
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ejecutante',
            field=models.ForeignKey(db_column='ejecutante_id', null=True, on_delete=models.SET('Trabajador eliminado'), related_name='ejecutante', to='SISGDDO.trabajador', verbose_name='Trabajador que responde a la incidencia'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(max_length=250, null=True, verbose_name='Estado de la incidencia*'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Proceso eliminado'), to='base.process', verbose_name='Proceso que da respuesta a la incidencia'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='reporta',
            field=models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado'), related_name='reporta', to='SISGDDO.trabajador', verbose_name='Trabajador que reporta la incidencia*'),
        ),
        migrations.AddField(
            model_name='planesdetrabajo',
            name='nivelorganizacional',
            field=models.CharField(max_length=80, null=True, verbose_name='Nivel*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2023-06-07', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2023-06-07', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.CreateModel(
            name='TareasPlan',
            fields=[
                ('numero', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='No.*')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Descripcion*')),
                ('día', models.PositiveIntegerField(verbose_name='Día de reunion*')),
                ('hora', models.TimeField(blank=True, verbose_name='Hora Programada*')),
                ('lugar', models.CharField(max_length=80, verbose_name='Lugar Previsto*')),
                ('participantes', models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), related_name='participantes', to='SISGDDO.trabajador', verbose_name='Trabajadores que Paticipan*')),
                ('preside', models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), to='SISGDDO.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='planesdetrabajo',
            name='tareas',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tarea eliminada de la Base de datos'), related_name='tareas', to='SISGDDO.tareasplan', verbose_name='Tareas del plan*'),
        ),
    ]
