# Generated by Django 2.2.7 on 2020-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0019_auto_20201219_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspecto_medir_indicadoreficacia',
            name='calificacion_asp',
            field=models.IntegerField(null=True, verbose_name='Calificación*'),
        ),
        migrations.AlterField(
            model_name='indicador_eficacia',
            name='calif_ind',
            field=models.IntegerField(null=True, verbose_name='Calificación*'),
        ),
    ]
