# Generated by Django 2.2.7 on 2020-12-19 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0020_auto_20201219_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador_eficacia',
            name='calif_ind',
        ),
    ]
