# Generated by Django 2.2.7 on 2020-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0022_remove_aspecto_medir_indicadoreficacia_calificacion_asp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspecto_medir_indicadoreficacia',
            name='nombre_asp',
            field=models.CharField(max_length=200, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='indicador_eficacia',
            name='nombre_ind',
            field=models.CharField(max_length=200, verbose_name='Nombre del Indicador*'),
        ),
    ]
