# Generated by Django 2.2.7 on 2020-12-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0023_auto_20201219_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficacia',
            name='calificacion_aspecto',
            field=models.IntegerField(null=True, verbose_name='Calificación del Aspecto*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='calificacion_indicador',
            field=models.IntegerField(null=True, verbose_name='Calificación del Indicador*'),
        ),
    ]
