# Generated by Django 2.2.7 on 2020-12-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0024_auto_20201219_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='eficacia',
            name='IndicadorEficacia',
            field=models.ForeignKey(default=19122020, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.indicador_eficacia', verbose_name='Indicador*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='aspecto_Medir_IndicadorEficacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.aspecto_Medir_IndicadorEficacia', verbose_name='Aspecto*'),
        ),
    ]
