# Generated by Django 2.2.7 on 2021-01-03 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0026_indicador_eficacia_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador_eficacia',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proceso', verbose_name='Proceso'),
        ),
    ]
