# Generated by Django 2.2.7 on 2021-01-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0027_auto_20210103_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspecto_medir_indicadoreficacia',
            name='nombre_asp',
            field=models.CharField(max_length=255, verbose_name='Nombre*'),
        ),
    ]
