# Generated by Django 2.2.7 on 2021-01-04 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0028_auto_20210103_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='anno',
            field=models.IntegerField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
    ]
