# Generated by Django 2.2.7 on 2021-01-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0029_auto_20210104_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosi',
            name='idioma',
        ),
        migrations.AddField(
            model_name='sosi',
            name='idioma',
            field=models.ManyToManyField(to='SISGDDO.idioma', verbose_name='Idioma*'),
        ),
    ]
