# Generated by Django 2.2.7 on 2021-01-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0030_auto_20210104_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspecto_medir_indicadoreficacia',
            name='calificacion_asp',
            field=models.IntegerField(null=True, verbose_name='Calificación*'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='ci',
            field=models.CharField(default=-1, max_length=11, verbose_name='Carnet de Identidad*'),
        ),
    ]
