# Generated by Django 2.2.7 on 2021-01-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0031_auto_20210106_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eficacia',
            name='IndicadorEficacia',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='aspecto_Medir_IndicadorEficacia',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='calificacion_aspecto',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='calificacion_indicador',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='ind_eficacia',
        ),
    ]
