# Generated by Django 2.2.7 on 2021-01-11 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0033_indicador_eficacia_calif_ind'),
    ]

    operations = [
        migrations.CreateModel(
            name='clasificacionincidencias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clasificacion', models.CharField(max_length=15, verbose_name='Clasificación')),
            ],
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.clasificacionincidencias', verbose_name='Clasificaión'),
        ),
    ]
