# Generated by Django 2.2.7 on 2021-01-11 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0034_auto_20210111_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencias',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.clasificacionincidencias', verbose_name='Clasificación'),
        ),
    ]
