# Generated by Django 2.2.7 on 2021-01-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0035_auto_20210111_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='es_cuadro',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Es Cuadro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fotocuadro',
            field=models.ImageField(blank=True, default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Imagen del Cuadro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='fotoreserva',
            field=models.ImageField(blank=True, default='foto/userDefault1.png', null=True, upload_to='foto/', verbose_name='Imagen de la Reserva'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='planillacuadro',
            field=models.FileField(blank=True, default='foto/userDefault1.png', null=True, upload_to='planillas/', verbose_name='Planilla del Cuadro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='planillareserva',
            field=models.FileField(blank=True, default='foto/userDefault1.png', null=True, upload_to='planillas/', verbose_name='Planilla de la Reserva'),
        ),
    ]
