# Generated by Django 2.2.7 on 2021-01-23 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0037_auto_20210111_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambiarLogotipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Cambio del Logotipo')),
                ('logo', models.ImageField(default='logo/logoSIG.jpg', upload_to='logo', verbose_name='Logo*')),
            ],
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
    ]
