# Generated by Django 2.2.7 on 2021-01-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0038_auto_20210123_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default=datetime.datetime(2021, 1, 23, 17, 3, 17, 359877), verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='logo',
            field=models.ImageField(upload_to='logo/logoSIG.jpg', verbose_name='Logo*'),
        ),
    ]
