# Generated by Django 2.2.7 on 2021-01-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0039_auto_20210123_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-01-23', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
