# Generated by Django 2.2.7 on 2021-01-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0040_auto_20210123_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='logo',
            field=models.ImageField(upload_to='media/logo/logoSIG.jpg', verbose_name='Logo*'),
        ),
    ]
