# Generated by Django 2.2.7 on 2021-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0042_auto_20210123_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='logo',
            field=models.ImageField(upload_to='logo/', verbose_name='Logo*'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='planillacuadro',
            field=models.FileField(blank=True, null=True, upload_to='planillas/', verbose_name='Planilla del Cuadro'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='planillareserva',
            field=models.FileField(blank=True, null=True, upload_to='planillas/', verbose_name='Planilla de la Reserva'),
        ),
    ]
