# Generated by Django 2.2.7 on 2021-01-23 20:56

import SISGDDO.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0043_auto_20210123_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='logo',
            field=models.ImageField(storage=SISGDDO.storage.OverwriteStorage(), upload_to='logo/', verbose_name='Logo*'),
        ),
    ]
