# Generated by Django 2.2.7 on 2021-01-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0044_auto_20210123_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspecto_medir_indicadoreficacia',
            name='nombre_asp',
            field=models.CharField(max_length=500, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-01-28', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
