# Generated by Django 2.2.7 on 2021-01-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0045_auto_20210128_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicador_eficacia',
            name='nombre_ind',
            field=models.CharField(max_length=500, verbose_name='Nombre del Indicador*'),
        ),
    ]
