# Generated by Django 2.2.7 on 2021-05-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0047_auto_20210501_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='nombre_Coleccion',
            field=models.CharField(max_length=55, unique=True, verbose_name='Línea Temática'),
        ),
    ]
