# Generated by Django 2.2.7 on 2021-05-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0048_auto_20210501_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-05-02', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='cod_proyecto',
            field=models.CharField(max_length=55, verbose_name='Código del Proyecto'),
        ),
    ]
