# Generated by Django 2.2.7 on 2021-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0050_auto_20210502_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='idioma',
            field=models.ManyToManyField(to='SISGDDO.idioma', verbose_name='Idioma*'),
        ),
    ]
