# Generated by Django 2.2.7 on 2021-05-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0051_auto_20210502_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='autor',
            field=models.CharField(max_length=100, null=True, verbose_name='Autor'),
        ),
    ]
