# Generated by Django 2.2.7 on 2021-05-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0052_auto_20210502_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(max_length=500, verbose_name='Nombre del Proyecto'),
        ),
    ]
