# Generated by Django 2.2.7 on 2021-05-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0053_auto_20210502_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-05-03', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proyecto'),
        ),
    ]
