# Generated by Django 2.2.7 on 2021-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0054_auto_20210503_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatos',
            name='nombre_Formato',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre*'),
        ),
    ]
