# Generated by Django 2.2.7 on 2021-05-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0056_auto_20210507_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-05-11', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(max_length=355, verbose_name='Nombre del Proyecto'),
        ),
    ]
