# Generated by Django 2.2.7 on 2021-05-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0058_auto_20210515_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='fecha_inicio_cuadro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio como cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_inicio_reserva',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio como reserva de cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_terminacion_cuadro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de terminación como cuadro'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='fecha_terminacion_reserva',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de terminación como reserva de cuadro'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-05-22', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='no_conformidad',
            name='fecha_cierre',
            field=models.DateTimeField(help_text='la fecha debe ser Día/Mes/Año Hora:Min:Seg ejemplo 01/01/2020 00:00:00', verbose_name='Fecha Cierre*'),
        ),
    ]
