# Generated by Django 2.2.7 on 2021-05-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0060_auto_20210529_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='permisos_personalizados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('grafico_RH', 'Ver grafico de las personas en el grupo de RRHH'), ('grafico_Cap', 'Ver grafico de las personas en el grupo de RRHH'), ('grafico_CA', 'Ver grafico de las personas en el grupo de RRHH'), ('grafico_D', 'Ver grafico de las personas en el grupo de RRHH'), ('grafico_I', 'Ver grafico de las personas en el grupo de RRHH'), ('grafico_Admin', 'Ver grafico de las personas en el grupo de RRHH')],
            },
        ),
    ]
