# Generated by Django 2.2.7 on 2021-06-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0061_permisos_personalizados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permisos_personalizados',
            options={'permissions': [('grafico_RH', 'Ver grafico de RRHH'), ('grafico_Cap', 'Ver grafico de CAP'), ('grafico_CA', 'Ver grafico de C y A'), ('grafico_D', 'Ver grafico de Desarrolo'), ('grafico_I', 'Ver grafico de Innov'), ('grafico_Admin', 'Ver grafico de Admin')]},
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-01', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
