# Generated by Django 2.2.7 on 2021-06-03 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0063_auto_20210603_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_dictamen_tecnico',
            name='fecha_entreda',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='historico_dictamen_tecnico',
            name='fecha_envio_resultado',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Envío de Resultados'),
        ),
    ]
