# Generated by Django 2.2.7 on 2021-06-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0064_auto_20210603_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_interna',
            name='titulo_inf',
            field=models.CharField(max_length=60, verbose_name='Título del Informe*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-08', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
