# Generated by Django 2.2.7 on 2021-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0065_auto_20210608_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones_correptivas',
            name='accion_tomar',
            field=models.CharField(max_length=255, verbose_name='Acciones a tomar*'),
        ),
        migrations.AlterField(
            model_name='acciones_prevenntivas',
            name='accion_tomar',
            field=models.CharField(max_length=255, verbose_name='Accion a tomar*'),
        ),
    ]
