# Generated by Django 2.2.7 on 2021-06-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0066_auto_20210608_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-09', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='lenguaje_prog',
            name='version_Lenguaje',
            field=models.FloatField(blank=True, null=True, verbose_name='Versión del Lenguaje*'),
        ),
    ]
