# Generated by Django 2.2.7 on 2021-06-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0067_auto_20210609_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eficacia',
            name='eficaz',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Eficaz*'),
        ),
    ]
