# Generated by Django 2.2.7 on 2021-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0069_auto_20210610_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-14', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
