# Generated by Django 2.2.7 on 2021-06-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0070_auto_20210614_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-15', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
