# Generated by Django 2.2.7 on 2021-06-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0071_auto_20210615_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-17', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
