# Generated by Django 2.2.7 on 2021-06-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0073_auto_20210619_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='eval_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eval_por', to='SISGDDO.trabajador', verbose_name='Evaluado por*'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='no_dictamen',
            field=models.IntegerField(auto_created=True, max_length=6, verbose_name='No. de Dictamen'),
        ),
    ]
