# Generated by Django 2.2.7 on 2021-06-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0074_auto_20210619_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdos_consejillo',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Número de Acuerdo'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='no_dictamen',
            field=models.IntegerField(max_length=6, verbose_name='No. de Dictamen'),
        ),
    ]
