# Generated by Django 2.2.7 on 2021-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0075_auto_20210619_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='no_dictamen',
            field=models.CharField(max_length=6, verbose_name='No. de Dictamen'),
        ),
    ]
