# Generated by Django 2.2.7 on 2021-06-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0076_auto_20210619_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='abreviatura',
            field=models.CharField(max_length=3, verbose_name='Abreviatura*'),
        ),
        migrations.AlterField(
            model_name='tipo_de_licencias',
            name='no_licencia',
            field=models.CharField(max_length=10, verbose_name='Número de Licencia'),
        ),
    ]
