# Generated by Django 2.2.7 on 2021-06-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0077_auto_20210619_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccion',
            name='anno',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
    ]
