# Generated by Django 2.2.7 on 2021-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0078_auto_20210619_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_externa',
            name='titulo_inf',
            field=models.CharField(max_length=60, verbose_name='Título del Informe*'),
        ),
        migrations.AlterField(
            model_name='auditoria_interna',
            name='documentos_referencia',
            field=models.CharField(max_length=50, verbose_name='Documentos de Referencia*'),
        ),
        migrations.AlterField(
            model_name='auditoria_interna',
            name='objetivos',
            field=models.CharField(max_length=50, verbose_name='Objetivos*'),
        ),
        migrations.AlterField(
            model_name='auditoria_interna',
            name='periodo_comprueba',
            field=models.CharField(max_length=25, verbose_name='Período de Comprueba*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-21', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='clasificacionincidencias',
            name='nombre_clasificacion',
            field=models.CharField(max_length=10, verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='no_dictamen',
            field=models.CharField(max_length=7, verbose_name='No. de Dictamen'),
        ),
        migrations.AlterField(
            model_name='entradas_proyecto',
            name='documentacion',
            field=models.CharField(max_length=60, verbose_name='Documentación*'),
        ),
        migrations.AlterField(
            model_name='formatos',
            name='nombre_Formato',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre*'),
        ),
        migrations.AlterField(
            model_name='lenguaje_prog',
            name='version_Lenguaje',
            field=models.FloatField(blank=True, max_length=3, null=True, verbose_name='Versión del Lenguaje*'),
        ),
        migrations.AlterField(
            model_name='no_conformidad',
            name='nombre_conformifdad',
            field=models.CharField(max_length=50, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='nombre_Proceso',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre del Proceso*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='resolusion_jefe_proyecto',
            field=models.CharField(max_length=8, verbose_name='Resolución de jefe de proyecto*'),
        ),
        migrations.AlterField(
            model_name='sistema_operativo',
            name='version_Sistema',
            field=models.FloatField(max_length=3, verbose_name='Versión del Sistema*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='cod_proyecto',
            field=models.CharField(max_length=50, verbose_name='Código del Proyecto'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proyecto'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='persona_entrega',
            field=models.CharField(max_length=50, verbose_name='Trabajador que Entrega'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='persona_recibe',
            field=models.CharField(max_length=50, verbose_name='Trabajador que Recibe'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='ubicacion_salv',
            field=models.CharField(max_length=10, verbose_name='Ubicación de Salva*'),
        ),
    ]
