# Generated by Django 2.2.7 on 2021-06-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0079_auto_20210621_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='numero_salva',
            field=models.IntegerField(verbose_name='Número de Salva*'),
        ),
    ]
