# Generated by Django 2.2.7 on 2021-06-22 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0080_auto_20210621_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-22', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.clasificacionincidencias', verbose_name='Clasificación*'),
        ),
        migrations.AlterField(
            model_name='no_conformidad',
            name='nombre_conformifdad',
            field=models.CharField(max_length=50, verbose_name='Asunto*'),
        ),
    ]
