# Generated by Django 2.2.7 on 2021-06-22 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0081_auto_20210622_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_entrega',
            field=models.DateField(verbose_name='Fecha de Entrega*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Inicio*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_terminacion',
            field=models.DateField(verbose_name='Fecha de Terminación*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.IntegerField(max_length=5, primary_key=True, serialize=False, unique=True, verbose_name='Número de Proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='anno',
            field=models.IntegerField(max_length=4, verbose_name='Año*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='autor',
            field=models.CharField(max_length=50, null=True, verbose_name='Autor*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='cod_proyecto',
            field=models.CharField(max_length=50, verbose_name='Código del Proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(max_length=255, verbose_name='Nombre del Proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='persona_entrega',
            field=models.CharField(max_length=50, verbose_name='Trabajador que Entrega*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='persona_recibe',
            field=models.CharField(max_length=50, verbose_name='Trabajador que Recibe*'),
        ),
        migrations.AlterField(
            model_name='tipo_de_licencias',
            name='no_licencia',
            field=models.CharField(max_length=10, verbose_name='Número de Licencia*'),
        ),
    ]
