# Generated by Django 2.2.7 on 2021-06-22 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0082_auto_20210622_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=60, verbose_name='Nombre del Proyecto*'),
        ),
    ]
