# Generated by Django 2.2.7 on 2021-06-23 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0083_auto_20210622_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='tratamiento',
            field=models.CharField(max_length=60, verbose_name='Tratamiento*'),
        ),
        migrations.AlterField(
            model_name='acuerdos_consejillo',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='Número de Acuerdo*'),
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='metodos_prueba',
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='metodos_prueba',
            field=models.ManyToManyField(to='SISGDDO.metodosprueba', verbose_name='Métodos de Prueba*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-23', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='fecha',
            field=models.DateField(verbose_name='Fecha*'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='no_dictamen',
            field=models.CharField(max_length=7, verbose_name='No. de Dictamen*'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='nombre_capitulos',
            field=models.CharField(max_length=25, verbose_name='Nombre de los Capítulos*'),
        ),
        migrations.AlterField(
            model_name='entradas_proyecto',
            name='no_entrada',
            field=models.IntegerField(verbose_name='Número de Entrada*'),
        ),
        migrations.AlterField(
            model_name='entradas_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proyecto', verbose_name='Proyecto*'),
        ),
        migrations.AlterField(
            model_name='historico_dictamen_tecnico',
            name='fecha_entreda',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Entrega*'),
        ),
        migrations.AlterField(
            model_name='historico_dictamen_tecnico',
            name='fecha_envio_resultado',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Envío de Resultados*'),
        ),
        migrations.AlterField(
            model_name='historico_entradas_proyectos',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Número de Proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='anno',
            field=models.CharField(max_length=4, verbose_name='Año*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='numero_salva',
            field=models.CharField(max_length=7, verbose_name='Número de Salva*'),
        ),
        migrations.DeleteModel(
            name='tratamiento',
        ),
    ]
