# Generated by Django 2.2.7 on 2021-06-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0084_auto_20210623_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='cargo',
            field=models.CharField(max_length=60, null=True, verbose_name='Cargo*'),
        ),
    ]
