# Generated by Django 2.2.7 on 2021-06-24 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0086_auto_20210624_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictamen_tecnico',
            name='especialista_calidad',
        ),
    ]
