# Generated by Django 2.2.7 on 2021-06-24 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0087_remove_dictamen_tecnico_especialista_calidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictamen_tecnico',
            name='area',
        ),
    ]
