# Generated by Django 2.2.7 on 2021-06-24 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0093_auto_20210624_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico_dictamen_tecnico',
            name='fecha_envio_resultado',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha de Envío de Resultados*'),
        ),
    ]
