# Generated by Django 2.2.7 on 2021-06-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0095_auto_20210624_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_interna',
            name='asunto',
            field=models.CharField(max_length=60, verbose_name='Asuntos*'),
        ),
    ]
