# Generated by Django 2.2.7 on 2021-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0096_auto_20210624_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria_interna',
            name='objetivos',
            field=models.CharField(max_length=255, verbose_name='Objetivos*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-25', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
