# Generated by Django 2.2.7 on 2021-06-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0098_auto_20210625_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_medidas',
            name='actividad',
            field=models.CharField(max_length=50, verbose_name='Actividad*'),
        ),
        migrations.AlterField(
            model_name='plan_medidas',
            name='titulo_doc',
            field=models.CharField(max_length=80, verbose_name='Título del Documento*'),
        ),
    ]
