# Generated by Django 2.2.7 on 2021-06-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0099_auto_20210625_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones_prevenntivas',
            name='accion_tomar',
            field=models.CharField(max_length=255, verbose_name='Acciones a tomar*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2021-06-26', verbose_name='Fecha de Cambio del Logotipo'),
        ),
    ]
