# Generated by Django 2.2.7 on 2021-06-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0101_auto_20210626_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='cod_proyecto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código del Proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='nombre_proy_prod',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Proyecto*'),
        ),
    ]
