# Generated by Django 2.2.7 on 2022-09-09 22:21

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0102_auto_20210626_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='accion_realizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha acción realizada*')),
                ('nombre_accion', models.CharField(max_length=150, verbose_name='Nombre acción*')),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre y apellidos*')),
            ],
        ),
        migrations.CreateModel(
            name='conclusion_adicional',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.proyecto')),
                ('fecha', models.DateField(verbose_name='Fecha de la conclusión adicional*')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion de la conclusión adicional')),
            ],
            bases=('SISGDDO.proyecto',),
        ),
        migrations.CreateModel(
            name='dato_adicional',
            fields=[
                ('proyecto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.proyecto')),
                ('fecha', models.DateField(verbose_name='Fecha del dato adicional*')),
                ('descripcion', models.TextField(max_length=250, verbose_name='Descripcion del dato adicional')),
            ],
            bases=('SISGDDO.proyecto',),
        ),
        migrations.CreateModel(
            name='estado_incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=25, verbose_name='Estado de la incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='estado_licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de estado*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_propiedad_intelectual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de estado*')),
            ],
        ),
        migrations.CreateModel(
            name='formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='fuente_financiamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Fuente de financiamiento*')),
            ],
        ),
        migrations.CreateModel(
            name='incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de recepcion de la incidencia*')),
                ('fecha_cierre', models.DateField(verbose_name='Fecha de cierre de la incidencia')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción de la incidencia')),
                ('respuesta', models.TextField(max_length=250, verbose_name='Respuesta dada a la incidencia')),
                ('estado', models.ForeignKey(on_delete=models.SET('Estado eliminado'), to='SISGDDO.estado_incidencia', verbose_name='Estado de la incidencia')),
            ],
        ),
        migrations.CreateModel(
            name='indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre del indicador')),
                ('evaluacion', models.FloatField(verbose_name='Evaluación del indicador')),
            ],
        ),
        migrations.CreateModel(
            name='licencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10000, unique=True, verbose_name='Número licencia')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Nombre licencia*')),
                ('fecha_otorgamiento', models.DateField(verbose_name='Fecha otorgamiento*')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha vencimiento*')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SISGDDO.entidad', verbose_name='Entidad*')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SISGDDO.estado_licencia', verbose_name='Estado de la licencia*')),
            ],
        ),
        migrations.CreateModel(
            name='linea_tematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Línea temática')),
                ('anno', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año')),
            ],
        ),
        migrations.CreateModel(
            name='notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad de notificaciones*')),
                ('titulo', models.CharField(max_length=60, verbose_name='Título notificación*')),
                ('licencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.licencia', verbose_name='Licencia*')),
            ],
        ),
        migrations.CreateModel(
            name='premio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del premio*')),
                ('fecha', models.DateTimeField(verbose_name='Fecha*')),
                ('premio', models.BooleanField(default=False, verbose_name='Premio o Reconocimiento*')),
                ('entidad', models.ForeignKey(on_delete=models.SET('CITMATEL'), to='SISGDDO.entidad', verbose_name='Entidad*')),
            ],
        ),
        migrations.CreateModel(
            name='propiedad_intelectual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10000, unique=True, verbose_name='Número')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud*')),
                ('fecha_otorgamiento', models.DateField(verbose_name='Fecha de otorgamiento*')),
                ('marca', models.CharField(max_length=80, verbose_name='Marca*')),
                ('certificado', models.FileField(upload_to='certifico/', verbose_name='Certifico propiedad intelectual')),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SISGDDO.estado_propiedad_intelectual', verbose_name='Estado de la licencia*')),
            ],
        ),
        migrations.CreateModel(
            name='queja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10000, unique=True, verbose_name='Número licencia')),
                ('fecha_receppcion', models.DateTimeField(verbose_name='Fecha recepción*')),
                ('fecha_cierre', models.DateTimeField(verbose_name='Fecha cierre')),
                ('motivo', models.CharField(max_length=150, verbose_name='Motivo de la queja*')),
                ('cliente', models.ForeignKey(on_delete=models.SET('Cliente eliminado de la Base de datos'), to='SISGDDO.cliente', verbose_name='Cliente de la queja*')),
            ],
        ),
        migrations.CreateModel(
            name='tipo_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Tipo de proyecto*')),
            ],
        ),
        migrations.CreateModel(
            name='via_recepcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55, unique=True, verbose_name='Nombre vía de recepción*')),
            ],
        ),
        migrations.RemoveField(
            model_name='atencion_cliente_externo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='atencion_cliente_externo',
            name='no_conformidad_ptr',
        ),
        migrations.RemoveField(
            model_name='cenda',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='incidencias',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='incidencias',
            name='no_conformidad_ptr',
        ),
        migrations.RemoveField(
            model_name='indicador_eficacia',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='no_conformidad',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='no_conformidad',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='no_conformidad',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='tipo_de_licencias',
            name='entidad_emite',
        ),
        migrations.RemoveField(
            model_name='tipo_de_licencias',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='tipo_de_licencias',
            name='trabajador_responsable',
        ),
        migrations.RemoveField(
            model_name='area',
            name='nombre_Area',
        ),
        migrations.RemoveField(
            model_name='auditoria_externa',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='area',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='asunto',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='conclusiones',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='documentos_referencia',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='metodos_prueba',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='periodo_comprueba',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='plan_medidas',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='trabajadores',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='conformidad',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='eval_tot',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='direccion_sitio',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='documentacion',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='estado_entradas_proyecto',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='formatos',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='jefe_UEB_grupo',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='lenguaje_prog',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='no_entrada',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='sistema_operativo',
        ),
        migrations.RemoveField(
            model_name='entradas_proyecto',
            name='trabajador_calidad_interna',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='nombre_Idioma',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='proceso',
            name='nombre_Proceso',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cenda',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='no_contrato',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='resolusion_jefe_proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='sosi',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='cod_proyecto',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='coleccion',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='documentacion',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='fecha_salv',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='materia_prima',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='nombre_proy_prod',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='persona_recibe',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='ubicacion_salv',
        ),
        migrations.AddField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=65, unique=True, verbose_name='Nombre del Área', null = True),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to='dictamenes/', verbose_name='Informe de la auditoria*'),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='observaciones',
            field=models.CharField(max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to='dictamenes/', verbose_name='Informe de la auditoria*'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=models.SET('Proceso eliminado'), to='SISGDDO.proceso', verbose_name='Proceso'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=models.SET('Responsable eliminado'), to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-09-09', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='evaluado_por',
            field=models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), related_name='evaluado_por_eficacia', to='SISGDDO.trabajador', verbose_name='Evaluado por*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=models.SET('Trabajador eliminado de la Base de datos'), related_name='responsable_eficacia', to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='semestre',
            field=models.BooleanField(default=False, help_text='Si es False es el primer semestre si no es el segundo semestre', verbose_name='Semestre*'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='entregado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador que entrega'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.estado_entradas_proyecto', verbose_name='Estado entrada proyecto'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='fecha_entrada',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrada*'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='fecha_salida',
            field=models.DateField(null=True, verbose_name='Fecha de salida'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Nombre del idioma*', null = True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre del Proceso*', null = True),
        ),
        migrations.AddField(
            model_name='proceso',
            name='responsable',
            field=models.ManyToManyField(to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='calidad',
            field=models.ManyToManyField(related_name='especialista_calidad_proyecto', to='SISGDDO.trabajador', verbose_name='Especialista de la calidad*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Código del proyecto*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='consecutivo',
            field=models.IntegerField(null=True, unique=True, verbose_name='Número de proyecto*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='costo',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.0)], verbose_name='Costo del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='disennador',
            field=models.ManyToManyField(related_name='disennador_proyecto', to='SISGDDO.trabajador', verbose_name='Diseñador del proyecto'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='Fecha de cierre'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_entrada',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrada*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_extension',
            field=models.DateField(null=True, verbose_name='Fecha de extensión'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='observacion',
            field=models.CharField(max_length=250, null=True, verbose_name='Observaciones del proyecto'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='codigo',
            field=models.CharField(max_length=7, null=True, verbose_name='Codigo'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='fecha_entrega',
            field=models.DateField(null=True, verbose_name='Fecha de entrega*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='observaciones',
            field=models.CharField(max_length=255, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del proyecto o servicio a salvar*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='ubicacion_salva',
            field=models.CharField(max_length=8, null=True, verbose_name='Ubicación de la salva'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='disennador',
            field=models.BooleanField(default=False, verbose_name='Es el diseñador'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='especialista_calidad',
            field=models.BooleanField(default=False, verbose_name='Es el Especialista de la calidad'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='jefe_proyecto',
            field=models.BooleanField(default=False, verbose_name='Es el Jefe de proyecto'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='responsable',
            field=models.BooleanField(default=False, verbose_name='Es el Responsable'),
        ),
        migrations.AlterField(
            model_name='auditoria_externa',
            name='plan_medidas',
            field=models.FileField(blank=True, null=True, upload_to='dictamenes/', verbose_name='Plan de medidas*'),
        ),
        migrations.AlterField(
            model_name='auditoria_externa',
            name='resultados',
            field=models.BooleanField(default=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-09-09', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='disennador',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Dato eliminado de la base de datos'), related_name='trabajadores', to='SISGDDO.trabajador', verbose_name='Diseñador'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='eficaz',
            field=models.BooleanField(default=False, verbose_name='Eficaz*'),
        ),
        migrations.AlterField(
            model_name='historico_entradas_proyectos',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_proyectos', to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_terminacion',
            field=models.DateField(null=True, verbose_name='Fecha de fin*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='jefe_proyecto',
            field=models.ManyToManyField(to='SISGDDO.trabajador', verbose_name='Jefe del proyecto*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nombre del proyecto*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='anno',
            field=models.CharField(max_length=4, verbose_name='Año que corresponde*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('Área eliminada'), to='SISGDDO.area', verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='formatos',
            field=models.ManyToManyField(to='SISGDDO.formato', verbose_name='Formatos*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='numero_salva',
            field=models.CharField(max_length=7, verbose_name='Número de salva*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='persona_entrega',
            field=models.ForeignKey(on_delete=models.SET('Trabajador eliminado'), to='SISGDDO.trabajador', verbose_name='Trabajador que entrega*'),
        ),
        migrations.DeleteModel(
            name='aspecto_Medir_IndicadorEficacia',
        ),
        migrations.DeleteModel(
            name='atencion_cliente_externo',
        ),
        migrations.DeleteModel(
            name='CENDA',
        ),
        migrations.DeleteModel(
            name='clasificacionincidencias',
        ),
        migrations.DeleteModel(
            name='cliente_externo',
        ),
        migrations.DeleteModel(
            name='coleccion',
        ),
        migrations.DeleteModel(
            name='estado_no_conformidad',
        ),
        migrations.DeleteModel(
            name='formatos',
        ),
        migrations.DeleteModel(
            name='incidencias',
        ),
        migrations.DeleteModel(
            name='indicador_eficacia',
        ),
        migrations.DeleteModel(
            name='No_Conformidad',
        ),
        migrations.DeleteModel(
            name='tipo_de_licencias',
        ),
        migrations.AddField(
            model_name='queja',
            name='proceso',
            field=models.ForeignKey(on_delete=models.SET('Proceso eliminado de la Base de datos'), to='SISGDDO.proceso', verbose_name='Proceso*'),
        ),
        migrations.AddField(
            model_name='queja',
            name='via_recepcion',
            field=models.ForeignKey(on_delete=models.SET('Vía de recepción eliminada de la Base de datos'), to='SISGDDO.via_recepcion', verbose_name='Cliente de la queja*'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='premio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.premio', verbose_name='Premio*'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='propiedad_intelectual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.propiedad_intelectual', verbose_name='Propiedad intelectual*'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='proceso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='SISGDDO.proceso', verbose_name='Proceso*'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='responsable',
            field=models.ManyToManyField(help_text='Escoja el responsable', to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ForeignKey(on_delete=models.SET('Trabajador eliminado'), to='SISGDDO.trabajador', verbose_name='Trabajador que reporta la incidencia*'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='indicador',
            field=models.ManyToManyField(to='SISGDDO.indicador', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='formato',
            field=models.ManyToManyField(to='SISGDDO.formato', verbose_name='Formato*'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='indicadores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SISGDDO.indicador', verbose_name='Indicador'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='formato',
            field=models.ManyToManyField(to='SISGDDO.formato', verbose_name='Formatos del proyecto*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fuente_financiamiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.fuente_financiamiento', verbose_name='Fuente de financiamiento'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.tipo_proyecto', verbose_name='Tipo*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='linea_tematica',
            field=models.ManyToManyField(to='SISGDDO.linea_tematica', verbose_name='Línea Temática*'),
        ),
    ]
