# Generated by Django 2.2.7 on 2022-09-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0111_auto_20220911_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lenguaje_prog',
        ),
        migrations.DeleteModel(
            name='sistema_operativo',
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.AlterField(
            model_name='historico_entradas_proyectos',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_proyectos', to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='no',
            field=models.TextField(unique=True, verbose_name='Número licencia'),
        ),
    ]
