# Generated by Django 2.2.7 on 2022-09-15 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0112_auto_20220911_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='accion_indicador_objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre de la acción*')),
                ('evaluacion', models.FloatField(verbose_name='Evaluación de la acción*')),
            ],
        ),
        migrations.CreateModel(
            name='acuerdo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(null=True, unique=True, verbose_name='Número de acuerdo*')),
                ('fecha', models.DateField(help_text='Día/Mes/Año ejemplo 01/01/2020', verbose_name='Fecha de tomado el acuerdo*')),
                ('fecha_limite', models.DateField(help_text='Día/Mes/Año ejemplo 01/01/2020', verbose_name='Fecha de cumplimiento límite')),
                ('fecha_cumplimiento', models.DateField(help_text='Día/Mes/Año ejemplo 01/01/2020', verbose_name='Fecha de cumplido el acuerdo')),
                ('observaciones', models.TextField(null=True, verbose_name='Observaciones sobre el acuerdo*')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion_dibujo_modelo_industrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre clasificación de Dibujo y Modelo Industrial')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion_elemento_figurativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Clasificación de Elemento Figurativo')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion_patente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre clasificacion de patente')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion_productos_servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de clasificación*')),
                ('producto', models.BooleanField(default=False, verbose_name='Es un producto')),
                ('premio', models.BooleanField(default=False, verbose_name='Es un servicio')),
            ],
        ),
        migrations.CreateModel(
            name='clasificacion_viena',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de la clasificación de Viena')),
            ],
        ),
        migrations.CreateModel(
            name='estado_indicador_objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Nombre de estado*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_propiedad_industrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado de propiedad industrial*')),
            ],
        ),
        migrations.CreateModel(
            name='indicador_objetivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='Nombre del indicador*')),
                ('evaluacion', models.FloatField(verbose_name='Evaluación del indicador*')),
                ('estado', models.ForeignKey(null=True, on_delete=models.SET('Estado eliminado'), to='SISGDDO.estado_indicador_objetivos', verbose_name='Estado*')),
            ],
        ),
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre de modalidad*')),
            ],
        ),
        migrations.CreateModel(
            name='objetivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre de objetivo*')),
                ('fecha_definicion', models.DateField(verbose_name='Fecha en que se definió el objetivo*')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=65, null=True, verbose_name='Nombre del país')),
            ],
        ),
        migrations.CreateModel(
            name='propiedad_industrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre*')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de solicitud*')),
                ('no_solicitud', models.CharField(max_length=9, unique=True, verbose_name='Número de solicitud*')),
                ('no_certificado', models.CharField(max_length=9, unique=True, verbose_name='Número de Certificado*')),
                ('concedido_por', models.CharField(max_length=80, verbose_name='Concedido por')),
                ('tipo_documento', models.CharField(max_length=80, verbose_name='Tipo de documento legal')),
                ('vigente_hasta', models.DateField(verbose_name='Vigente hasta*')),
                ('observaciones', models.TextField(max_length=500, verbose_name='Observaciones')),
                ('clasificacion_dibujo_modelo_industrial', models.ForeignKey(on_delete=models.SET('Clasificación Dibujo y Modelo Industrial eliminado de la Base de datos'), to='SISGDDO.clasificacion_dibujo_modelo_industrial', verbose_name='Clasificación dibujo modelo industrial')),
                ('clasificacion_elemento_figurativo', models.ForeignKey(on_delete=models.SET('Clasificación de Elemento Figurativo eliminado de la Base de datos'), to='SISGDDO.clasificacion_elemento_figurativo', verbose_name='Clasificación de Elementos Figurativos')),
                ('clasificacion_patente', models.ForeignKey(on_delete=models.SET('Clasificación de Patente eliminada de la Base de datos'), to='SISGDDO.clasificacion_patente', verbose_name='Clasificación de patentes')),
                ('clasificacion_productos_servicios', models.ForeignKey(on_delete=models.SET('Clasificación de productos y servicios eliminada de la Base de datos'), to='SISGDDO.clasificacion_productos_servicios', verbose_name='Clasificación Productos y Servicios')),
                ('clasificacion_viena', models.ForeignKey(on_delete=models.SET('Clasificación de Viena eliminada de la Base de datos'), to='SISGDDO.clasificacion_viena', verbose_name='Clasificación de Viena')),
                ('estado', models.ForeignKey(on_delete=models.SET('Estado eliminado de la Base de datos'), to='SISGDDO.estado_propiedad_industrial', verbose_name='Estado de la licencia*')),
                ('modalidad', models.ForeignKey(on_delete=models.SET('Modalidad eliminada de la Base de datos*'), to='SISGDDO.modalidad', verbose_name='Modalidad*')),
                ('pais', models.ForeignKey(on_delete=models.SET('Pais eliminado'), to='SISGDDO.pais', verbose_name='País*')),
            ],
        ),
        migrations.RemoveField(
            model_name='area',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='estado_acuerdo',
            name='nombre_Estado',
        ),
        migrations.AddField(
            model_name='estado_acuerdo',
            name='nombre',
            field=models.CharField(max_length=25, null=True, verbose_name='Estado de acuerdo*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-09-15', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='dictamen_tecnico',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-09-15', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='historico_entradas_proyectos',
            name='entradas_proyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_proyectos', to='SISGDDO.entradas_proyecto', verbose_name='Entradas Proyectos'),
        ),
        migrations.DeleteModel(
            name='acuerdos_consejillo',
        ),
        migrations.AddField(
            model_name='objetivo',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='Área*'),
        ),
        migrations.AddField(
            model_name='indicador_objetivos',
            name='objetivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='SISGDDO.objetivo', verbose_name='Objetivo*'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='estado',
            field=models.ForeignKey(on_delete=models.SET('Estado eliminado'), to='SISGDDO.estado_acuerdo', verbose_name='Estado de acuerdo*'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='responsable',
            field=models.ManyToManyField(to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AddField(
            model_name='accion_indicador_objetivos',
            name='area',
            field=models.ForeignKey(null=True, on_delete=models.SET('Area eliminado de la BD'), to='SISGDDO.area', verbose_name='Area a la que pertenece*'),
        ),
        migrations.AddField(
            model_name='accion_indicador_objetivos',
            name='indicador_objetivos',
            field=models.ForeignKey(null=True, on_delete=models.SET('Indicador eliminado de la BD'), to='SISGDDO.indicador_objetivos', verbose_name='Indicador al que pertenece*'),
        ),
    ]
