# Generated by Django 2.2.7 on 2022-09-30 14:01

import SISGDDO.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0113_auto_20220915_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='aspecto_medir_eficacia_indicador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre de aspecto*')),
                ('calificacion', models.IntegerField(null=True, verbose_name='Calificación de aspecto*')),
            ],
        ),
        migrations.CreateModel(
            name='capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio*')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('resultado', models.CharField(max_length=10, verbose_name='Resultado del curso')),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones')),
                ('costo_diario_trabajador', models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Costo diario del trabajador en la capacitación')),
            ],
        ),
        migrations.CreateModel(
            name='consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default='Some String', max_length=10, null=True, unique=True, verbose_name='Número de proyecto*')),
                ('codigo', models.CharField(default='Some String', max_length=10, null=True, unique=True, verbose_name='Código del proyecto*')),
                ('fecha_entrada', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrada*')),
                ('nombre_proyecto', models.CharField(default='Some String', max_length=250, null=True, unique=True, verbose_name='Nombre del proyecto*')),
                ('fecha_terminacion', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de fin')),
                ('fecha_extension', models.DateField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de extensión')),
                ('fecha_inicio', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de inicio*')),
                ('fecha_cierre', models.DateField(default=datetime.datetime.now, null=True, verbose_name='Fecha de cierre*')),
                ('costo', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.0)], verbose_name='Costo del proyecto*')),
                ('observacion', models.CharField(blank=True, default='Some String', max_length=250, null=True, verbose_name='Observaciones del proyecto')),
                ('informe', models.FileField(blank=True, null=True, upload_to=SISGDDO.models.consecutivo.ruta, verbose_name='Expediente de consecutivo')),
                ('area', models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='Área*')),
                ('estado', models.ForeignKey(on_delete=models.SET('Estado eliminado de la BD'), to='SISGDDO.estado_proyecto', verbose_name='Estado*')),
                ('formato', models.ManyToManyField(to='SISGDDO.formato', verbose_name='Formatos del proyecto*')),
                ('fuente_financiamiento', models.ForeignKey(null=True, on_delete=models.SET('Fuente de financiamiento eliminada de la BD'), to='SISGDDO.fuente_financiamiento', verbose_name='Fuente de financiamiento')),
                ('linea_tematica', models.ForeignKey(blank=True, null=True, on_delete=models.SET('Línea temática eliminada de la BD'), to='SISGDDO.linea_tematica', verbose_name='Línea Temática')),
            ],
        ),
        migrations.CreateModel(
            name='consecutivo_roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.consecutivo', verbose_name='Consecutivo*')),
            ],
        ),
        migrations.CreateModel(
            name='estado_curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_curso', models.CharField(max_length=25, verbose_name='Estado del curso')),
            ],
        ),
        migrations.CreateModel(
            name='modo_formacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacion', models.CharField(max_length=25, verbose_name='Modo de formación')),
            ],
        ),
        migrations.CreateModel(
            name='rol_consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, null=True, unique=True, verbose_name='Nombre clasificacion de patente*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejecutante', models.BooleanField(default=False, verbose_name='Si es False es Trabajador, si es True es Ejecutante*')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=40, verbose_name='Nombre del rol*')),
            ],
        ),
        migrations.RemoveField(
            model_name='formacion_personal',
            name='capacitacion_adquirida',
        ),
        migrations.RemoveField(
            model_name='historico_dictamen_tecnico',
            name='dictamen_tecnico',
        ),
        migrations.RemoveField(
            model_name='historico_entradas_proyectos',
            name='entradas_proyectos',
        ),
        migrations.RemoveField(
            model_name='historico_entradas_proyectos',
            name='entregado_por',
        ),
        migrations.RemoveField(
            model_name='historico_entradas_proyectos',
            name='recibida_por',
        ),
        migrations.RemoveField(
            model_name='propiedad_intelectual',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='valoracion_encuesta',
            name='elaborado_por',
        ),
        migrations.RemoveField(
            model_name='valoracion_encuesta',
            name='organismos',
        ),
        migrations.RenameField(
            model_name='auditoria_interna',
            old_name='fecha_aud',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='sosi',
            old_name='persona_entrega',
            new_name='especialista',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='nombre_trabajador',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='auditoria_externa',
            name='fecha_emision',
        ),
        migrations.RemoveField(
            model_name='auditoria_externa',
            name='no_registro',
        ),
        migrations.RemoveField(
            model_name='auditoria_externa',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='auditoria_externa',
            name='titulo_inf',
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='titulo_inf',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='nombre_Curso',
        ),
        migrations.RemoveField(
            model_name='eficacia',
            name='proceso_ef',
        ),
        migrations.RemoveField(
            model_name='notificacion',
            name='propiedad_intelectual',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='calidad',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='disennador',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='jefe_proyecto',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='anno',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='area',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='formatos',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='linea_tematica',
        ),
        migrations.RemoveField(
            model_name='sosi',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='disennador',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='especialista_calidad',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='formacion_personal',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='jefe_proyecto',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='responsable',
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='nombre',
            field=models.CharField(max_length=25, null=True, verbose_name='Nombre del acuerdo*'),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='fecha',
            field=models.DateField(null=True, verbose_name='Fecha de emisión*'),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='registro',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de registro*'),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='titulo',
            field=models.CharField(max_length=150, null=True, verbose_name='Título del informe*'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='alcance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Alcance de la auditoría'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='criterios',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Criterios de la auditoría'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='objetivos',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Objetivos de la auditoría'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones de la auditoría'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='titulo',
            field=models.CharField(max_length=150, null=True, verbose_name='Título del informe*'),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion_diaria',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duración del curso en horas'),
        ),
        migrations.AddField(
            model_name='curso',
            name='entidad',
            field=models.ForeignKey(null=True, on_delete=models.SET('Entidad eliminada'), to='SISGDDO.entidad', verbose_name='Entidad*'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='curso',
            name='fecha_inicio',
            field=models.DateField(null=True, verbose_name='Fecha de inicio*'),
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del curso*'),
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.FloatField(blank=True, null=True, verbose_name='Precio del curso'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='proceso',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Proceso eliminado'), to='SISGDDO.proceso', verbose_name='Proceso que da respuesta a la incidencia'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='propiedad_industrial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.propiedad_industrial', verbose_name='Propiedad intelectual*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='linea_tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Línea temática eliminada de la BD'), to='SISGDDO.linea_tematica', verbose_name='Línea Temática'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='no',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de proyecto*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de entrega*'),
        ),
        migrations.AlterField(
            model_name='auditoria_externa',
            name='entidad',
            field=models.ForeignKey(on_delete=models.SET('Entidad eliminada'), to='SISGDDO.entidad', verbose_name='Entidad*'),
        ),
        migrations.AlterField(
            model_name='auditoria_externa',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='auditoria_interna',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=models.SET('Proceso eliminado'), to='SISGDDO.proceso', verbose_name='Proceso*'),
        ),
        migrations.RemoveField(
            model_name='auditoria_interna',
            name='responsable',
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='responsable',
            field=models.ManyToManyField(to='SISGDDO.trabajador', verbose_name='Responsable*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-09-30', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-09-30', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.CharField(max_length=250, verbose_name='Descripción de la incidencia*'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_cierre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de cierre de la incidencia'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='respuesta',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Respuesta dada a la incidencia'),
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='trabajador',
        ),
        migrations.AlterField(
            model_name='indicador',
            name='evaluacion',
            field=models.FloatField(verbose_name='Evaluación del indicador*'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre del indicador*'),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='proceso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proceso', verbose_name='Proceso*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='Área*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='consecutivo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.consecutivo', verbose_name='Consecutivo del proyecto*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='costo',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(0.0)], verbose_name='Costo del proyecto*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.ForeignKey(on_delete=models.SET('Estado eliminado de la BD'), to='SISGDDO.estado_proyecto', verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='Fecha de cierre*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_extension',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de extensión'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fuente_financiamiento',
            field=models.ForeignKey(null=True, on_delete=models.SET('Fuente de financiamiento eliminada de la BD'), to='SISGDDO.fuente_financiamiento', verbose_name='Fuente de financiamiento'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Nombre del proyecto*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones del proyecto'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de proyecto eliminado de la Base de datos'), to='SISGDDO.tipo_proyecto', verbose_name='Tipo*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='numero_salva',
            field=models.CharField(default='Some string', max_length=10, verbose_name='Número de salva*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='observaciones',
            field=models.CharField(blank=True, default='Some string', max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='ubicacion_salva',
            field=models.CharField(blank=True, default='Some string', max_length=10, null=True, verbose_name='Ubicación de la salva'),
        ),
        migrations.DeleteModel(
            name='dictamen_tecnico',
        ),
        migrations.DeleteModel(
            name='estado_propiedad_intelectual',
        ),
        migrations.DeleteModel(
            name='formacion_personal',
        ),
        migrations.DeleteModel(
            name='Historico_Dictamen_tecnico',
        ),
        migrations.DeleteModel(
            name='Historico_Entradas_proyectos',
        ),
        migrations.DeleteModel(
            name='organismo',
        ),
        migrations.DeleteModel(
            name='propiedad_intelectual',
        ),
        migrations.DeleteModel(
            name='Valoracion_encuesta',
        ),
        migrations.AddField(
            model_name='trabajador_proyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proyecto', verbose_name='Proyecto*'),
        ),
        migrations.AddField(
            model_name='trabajador_proyecto',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
        migrations.AddField(
            model_name='trabajador_incidencia',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.incidencia', verbose_name='Incidencia*'),
        ),
        migrations.AddField(
            model_name='trabajador_incidencia',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
        migrations.AddField(
            model_name='consecutivo_roles',
            name='rol',
            field=models.ForeignKey(on_delete=models.SET('Rol elimminado de la BD'), to='SISGDDO.rol_consecutivo', verbose_name='Nombre del rol*'),
        ),
        migrations.AddField(
            model_name='consecutivo_roles',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='roles',
            field=models.ManyToManyField(through='SISGDDO.consecutivo_roles', to='SISGDDO.trabajador', verbose_name='Rol en el proyecto*'),
        ),
        migrations.AddField(
            model_name='consecutivo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de proyecto eliminado de la Base de datos'), to='SISGDDO.tipo_proyecto', verbose_name='Tipo*'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='curso',
            field=models.ForeignKey(on_delete=models.SET('Curso eliminado de la BD'), to='SISGDDO.curso', verbose_name='Nombre del curso*'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='estado',
            field=models.ForeignKey(on_delete=models.SET('Estado del curso eliminado'), to='SISGDDO.estado_curso', verbose_name='Estado del curso'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=models.SET('Trabajador eliminado'), to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
        migrations.AddField(
            model_name='aspecto_medir_eficacia_indicador',
            name='indicador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.indicador', verbose_name='Indicador*'),
        ),
        migrations.AddField(
            model_name='curso',
            name='estado_curso',
            field=models.ForeignKey(null=True, on_delete=models.SET('Estado del curso eliminado'), to='SISGDDO.estado_curso', verbose_name='Estado del curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modo_formacion',
            field=models.ForeignKey(null=True, on_delete=models.SET('Modo de formación eliminado de la BD'), to='SISGDDO.modo_formacion', verbose_name='Modo de formación*'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='roles',
            field=models.ManyToManyField(through='SISGDDO.trabajador_proyecto', to='SISGDDO.trabajador', verbose_name='Rol en el proyecto*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='consecutivo_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.consecutivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='trabajador',
            field=models.ManyToManyField(through='SISGDDO.trabajador_incidencia', to='SISGDDO.trabajador', verbose_name='Trabajador o ejecutante*'),
        ),
    ]
