# Generated by Django 2.2.7 on 2022-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0114_auto_20220930_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consecutivo',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Código del proyecto*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='Fecha de cierre*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_extension',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de extensión'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='no',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Número de proyecto*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='nombre_proyecto',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='Nombre del proyecto*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones del proyecto'),
        ),
        migrations.AlterField(
            model_name='consecutivo_roles',
            name='rol',
            field=models.ForeignKey(on_delete=models.SET('Rol elimminado de la BD*'), to='SISGDDO.rol_consecutivo', verbose_name='Nombre del rol*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='numero_salva',
            field=models.CharField(max_length=10, verbose_name='Número de salva*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='ubicacion_salva',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Ubicación de la salva'),
        ),
    ]
