# Generated by Django 4.1.1 on 2022-10-07 00:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0115_auto_20220930_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='accion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(max_length=60, verbose_name='Tratamiento*')),
                ('fecha_cumplir', models.DateField(default=datetime.datetime.now, verbose_name='Fecha a Cumplir*')),
                ('seguimiento', models.CharField(max_length=60, verbose_name='Seguimiento*')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='trabajador_consecutivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.consecutivo', verbose_name='Consecutivo*')),
            ],
        ),
        migrations.RemoveField(
            model_name='acciones',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='acciones_correctivas',
            name='acciones_ptr',
        ),
        migrations.RemoveField(
            model_name='acciones_preventivas',
            name='acciones_ptr',
        ),
        migrations.RemoveField(
            model_name='consecutivo_roles',
            name='consecutivo',
        ),
        migrations.RemoveField(
            model_name='consecutivo_roles',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='consecutivo_roles',
            name='trabajador',
        ),
        migrations.DeleteModel(
            name='estado_dictamen',
        ),
        migrations.DeleteModel(
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='trabajador_incidencia',
            name='incidencia',
        ),
        migrations.RemoveField(
            model_name='trabajador_incidencia',
            name='trabajador',
        ),
        migrations.RenameField(
            model_name='acuerdo',
            old_name='estado',
            new_name='estado_acuerdo',
        ),
        migrations.RenameField(
            model_name='clasificacion_productos_servicios',
            old_name='premio',
            new_name='servicio',
        ),
        migrations.RenameField(
            model_name='entidad',
            old_name='nombre_Entidad',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='estado_proyecto',
            old_name='nombre_Estado',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre_proyecto',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='trabajador',
        ),
        migrations.RemoveField(
            model_name='premio',
            name='premio',
        ),
        migrations.AddField(
            model_name='accion_indicador_objetivos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='aspecto_medir_eficacia_indicador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='auditoria_externa',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='auditoria_interna',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='eficacia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='entradas_proyecto',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.proyecto', verbose_name='Proyecto*'),
        ),
        migrations.AddField(
            model_name='estado_curso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='estado_incidencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='indicador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='indicador_objetivos',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='licencia',
            name='observaciones',
            field=models.TextField(max_length=500, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='modo_formacion',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='premio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='premio',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='premios/', verbose_name='Planilla de la Reserva'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='proceso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='propiedad_industrial',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AddField(
            model_name='queja',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='anno',
            field=models.CharField(max_length=4, null=True, verbose_name='Año al que corresponde la salva'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor del proyecto'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='fecha_limite',
            field=models.DateField(help_text='Día/Mes/Año ejemplo 01/01/2020', verbose_name='Fecha límite para cumplir'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='numero',
            field=models.CharField(max_length=100000, null=True, unique=True, verbose_name='Número de acuerdo*'),
        ),
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-10-07', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-10-07', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='entidad',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo*'),
        ),
        migrations.AlterField(
            model_name='entradas_proyecto',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SISGDDO.estado_entradas_proyecto', verbose_name='Estado entrada proyecto'),
        ),
        migrations.AlterField(
            model_name='indicador_objetivos',
            name='nombre',
            field=models.CharField(max_length=80, null=True, unique=True, verbose_name='Nombre del indicador*'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre de objetivo*'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha*'),
        ),
        migrations.AlterField(
            model_name='premio',
            name='nombre',
            field=models.CharField(max_length=150, null=True, unique=True, verbose_name='Nombre del premio*'),
        ),
        migrations.AlterField(
            model_name='rol_consecutivo',
            name='nombre',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Rol del trabajador en el consecutivo*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='observaciones',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='trabajador_proyecto',
            name='rol',
            field=models.ForeignKey(on_delete=models.SET('Rol eliminado de la BD'), to='SISGDDO.rol_consecutivo', verbose_name='Rol*'),
        ),
        migrations.CreateModel(
            name='accion_correctiva',
            fields=[
                ('accion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.accion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Acción a tomar*')),
            ],
            bases=('SISGDDO.accion',),
        ),
        migrations.CreateModel(
            name='accion_preventiva',
            fields=[
                ('accion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SISGDDO.accion')),
                ('nombre', models.CharField(max_length=255, verbose_name='Acción a tomar*')),
            ],
            bases=('SISGDDO.accion',),
        ),
        migrations.AddField(
            model_name='trabajador_consecutivo',
            name='rol',
            field=models.ForeignKey(on_delete=models.SET('Rol eliminado de la BD'), to='SISGDDO.rol_consecutivo', verbose_name='Rol*'),
        ),
        migrations.AddField(
            model_name='trabajador_consecutivo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SISGDDO.trabajador', verbose_name='Trabajador*'),
        ),
        migrations.AddField(
            model_name='accion',
            name='responsable',
            field=models.ManyToManyField(to='SISGDDO.trabajador', verbose_name='Responsble*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='roles',
            field=models.ManyToManyField(through='SISGDDO.trabajador_consecutivo', to='SISGDDO.trabajador', verbose_name='Rol en el proyecto*'),
        ),
        migrations.AlterField(
            model_name='plan_medidas',
            name='acciones',
            field=models.ManyToManyField(to='SISGDDO.accion', verbose_name='Acciones*'),
        ),
        migrations.DeleteModel(
            name='acciones',
        ),
        migrations.DeleteModel(
            name='acciones_correctivas',
        ),
        migrations.DeleteModel(
            name='acciones_preventivas',
        ),
        migrations.DeleteModel(
            name='consecutivo_roles',
        ),
        migrations.DeleteModel(
            name='trabajador_incidencia',
        ),
    ]
