# Generated by Django 4.1.1 on 2022-10-07 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0116_accion_trabajador_consecutivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='rol_trabajador_proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True, unique=True, verbose_name='Rol del trabajador en el proyecto*')),
            ],
        ),
        migrations.RenameModel(
            old_name='rol_consecutivo',
            new_name='rol_trabajador_consecutivo',
        ),
        migrations.AlterField(
            model_name='trabajador_proyecto',
            name='rol',
            field=models.ForeignKey(on_delete=models.SET('Rol eliminado de la BD'), to='SISGDDO.rol_trabajador_proyecto', verbose_name='Rol*'),
        ),
    ]
