# Generated by Django 4.1.1 on 2022-10-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0119_alter_area_nombre_alter_cambiarlogotipo_fecha_cambio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=65, null=True, unique=True, verbose_name='Nombre del país'),
        ),
    ]
