# Generated by Django 4.1.1 on 2022-10-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0120_alter_pais_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado_acuerdo',
            name='nombre',
            field=models.CharField(max_length=25, null=True, unique=True, verbose_name='Estado de acuerdo*'),
        ),
    ]
