# Generated by Django 4.1.1 on 2022-10-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0121_alter_estado_acuerdo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(max_length=65, null=True, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='estado_proyecto',
            name='nombre',
            field=models.CharField(max_length=25, unique=True, verbose_name='Estado*'),
        ),
        migrations.AlterField(
            model_name='fuente_financiamiento',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Fuente de financiamiento*'),
        ),
        migrations.AlterField(
            model_name='indicador_objetivos',
            name='nombre',
            field=models.CharField(max_length=80, null=True, verbose_name='Nombre del indicador*'),
        ),
        migrations.AlterField(
            model_name='tipo_proyecto',
            name='nombre',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tipo de proyecto*'),
        ),
    ]
