# Generated by Django 4.1.1 on 2022-10-09 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0122_alter_area_nombre_alter_estado_proyecto_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_entradas_proyecto',
            old_name='nombre_Estado',
            new_name='nombre',
        ),
    ]
