# Generated by Django 4.1.1 on 2022-10-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0123_rename_nombre_estado_estado_entradas_proyecto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-10-10', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-10-10', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='linea_tematica',
            name='anno',
            field=models.DateField(blank=True, default='2022', null=True, verbose_name='Año'),
        ),
    ]
