# Generated by Django 4.1.1 on 2022-10-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0125_alter_linea_tematica_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_tematica',
            name='anno',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Año'),
        ),
    ]
