# Generated by Django 4.1.1 on 2022-10-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0126_alter_linea_tematica_anno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linea_tematica',
            name='nombre',
            field=models.CharField(max_length=55, unique=True, verbose_name='Nombre'),
        ),
    ]
