# Generated by Django 4.1.1 on 2022-10-25 00:18

import SISGDDO.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SISGDDO', '0128_alter_area_activo_alter_area_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiarlogotipo',
            name='fecha_cambio',
            field=models.DateField(default='2022-10-25', verbose_name='Fecha de Cambio del Logotipo'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='area',
            field=models.ForeignKey(on_delete=models.SET('Área eliminada de la BD'), to='SISGDDO.area', verbose_name='área*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='codigo',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='código*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='costo',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(9999999)], verbose_name='costo*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='estado',
            field=models.ForeignKey(on_delete=models.SET('Estado eliminado de la BD'), to='SISGDDO.estado_proyecto', verbose_name='estado*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_cierre',
            field=models.DateField(null=True, verbose_name='fecha de cierre*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_entrada',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de entrada*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_extension',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de extensión'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha de inicio*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fecha_terminacion',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='formato',
            field=models.ManyToManyField(to='SISGDDO.formato', verbose_name='formato*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='fuente_financiamiento',
            field=models.ForeignKey(null=True, on_delete=models.SET('Fuente de financiamiento eliminada de la BD'), to='SISGDDO.fuente_financiamiento', verbose_name='fuente de financiamiento*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='informe',
            field=models.FileField(blank=True, null=True, upload_to=SISGDDO.models.consecutivo.ruta, verbose_name='expediente'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='linea_tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('Línea temática eliminada de la BD'), to='SISGDDO.linea_tematica', verbose_name='línea temática'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='no',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='número*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='nombre_proyecto',
            field=models.CharField(max_length=250, null=True, unique=True, verbose_name='nombre*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='observacion',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='observacion'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='roles',
            field=models.ManyToManyField(through='SISGDDO.trabajador_consecutivo', to='SISGDDO.trabajador', verbose_name='rol*'),
        ),
        migrations.AlterField(
            model_name='consecutivo',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=models.SET('Tipo de proyecto eliminado de la Base de datos'), to='SISGDDO.tipo_proyecto', verbose_name='tipo*'),
        ),
        migrations.AlterField(
            model_name='eficacia',
            name='anno',
            field=models.DateField(default='2022-10-25', verbose_name='Año análisis de eficacia*'),
        ),
        migrations.AlterField(
            model_name='entradas_proyecto',
            name='fecha_entrada',
            field=models.DateField(default=datetime.datetime.now, verbose_name='fecha*'),
        ),
    ]
