# Generated by Django 4.1.3 on 2024-02-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(default='2024-02-07', verbose_name='fecha de entrega*'),
        ),
    ]
