# Generated by Django 4.1.3 on 2024-04-12 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0004_accion_control_etapa_control_etapa_estado_software_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subclasificacion',
            name='siglas',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='siglas*'),
        ),
        migrations.AlterField(
            model_name='entrada_proyecto',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_proyecto', to='xavi.estado_proyecto_dgca', verbose_name='Estado entrada proyecto'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x559155bd8860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-04-12', null=True, verbose_name='fecha de entrada*'),
        ),
    ]
