# Generated by Django 4.1.3 on 2024-04-24 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0006_cliente_alter_clasificacion_siglas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_aprobacion',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='registro_aprobacion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.cliente', verbose_name='cliente*'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x55db90f40860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-04-24', null=True, verbose_name='fecha de entrada*'),
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='xavi.cliente', verbose_name='cliente*')),
            ],
        ),
    ]
