# Generated by Django 4.1.3 on 2024-04-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0007_remove_registro_aprobacion_prioridad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='autor_sosi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True, verbose_name='nombre*')),
                ('activo', models.BooleanField(default=True, verbose_name='activo*')),
            ],
        ),
        migrations.AddField(
            model_name='sosi',
            name='colectivo',
            field=models.BooleanField(default=False, verbose_name='colectivo de autores'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x5638025ac860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-04-30', null=True, verbose_name='fecha de entrada*'),
        ),
        migrations.AddField(
            model_name='sosi',
            name='autor',
            field=models.ManyToManyField(to='xavi.autor_sosi', verbose_name='autor'),
        ),
    ]
