# Generated by Django 4.1.3 on 2024-05-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0008_autor_sosi_sosi_colectivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x555b3cfad860>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='archivo',
            field=models.URLField(blank=True, null=True, verbose_name='ruta del archivo'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, to='xavi.autor_sosi', verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-05-02', null=True, verbose_name='fecha de entrada*'),
        ),
    ]
