# Generated by Django 4.1.3 on 2024-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0009_alter_registro_reinicio_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x55c844a75860>', verbose_name='fecha de inicio del reinicio'),
        ),
    ]
