# Generated by Django 4.2.8 on 2024-05-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0010_alter_registro_reinicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='nombre*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='número*'),
        ),
        migrations.AlterField(
            model_name='registro_aprobacion',
            name='financiamiento',
            field=models.ManyToManyField(blank=True, null=True, through='xavi.financiamiento_proyecto', to='xavi.fuente_financiamiento', verbose_name='financiamiento*'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x00007FFF202BB650>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='archivo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ruta del archivo'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-05-18', null=True, verbose_name='fecha de entrada*'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='ubicacion_salva',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ubicación'),
        ),
    ]
