# Generated by Django 4.2.8 on 2024-05-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xavi', '0011_alter_cliente_codigo_alter_proyecto_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='nombre*'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=65, verbose_name='nombre*'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='codigo',
            field=models.CharField(max_length=10, null=True, verbose_name='código*'),
        ),
        migrations.AlterField(
            model_name='registro_reinicio',
            name='fecha_inicio',
            field=models.DateField(default='<built-in method now of type object at 0x00007FFF60BEB650>', verbose_name='fecha de inicio del reinicio'),
        ),
        migrations.AlterField(
            model_name='sosi',
            name='fecha',
            field=models.DateField(blank=True, default='2024-05-28', null=True, verbose_name='fecha de entrada*'),
        ),
    ]
